[build]
  functions = "functions"

[dev]
  functions = "functions"
  port = 8888
  targetPort = 9999
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
